In [62]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU,Dropout,Bidirectional,Conv1D


a = np.array(range(1,101))
x_predict = np.array(range(96,106))



In [63]:
def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]

print(x[:5:],"\n ========================== \n",y[:5:])

(96, 5)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 
 [5 6 7 8 9]


In [64]:
print(x.shape,y.shape)

(96, 4) (96,)


In [65]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),2,2)
print(x.shape)
print(x)

(96, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 2  3]
  [ 4  5]]

 [[ 3  4]
  [ 5  6]]

 [[ 4  5]
  [ 6  7]]

 [[ 5  6]
  [ 7  8]]

 [[ 6  7]
  [ 8  9]]

 [[ 7  8]
  [ 9 10]]

 [[ 8  9]
  [10 11]]

 [[ 9 10]
  [11 12]]

 [[10 11]
  [12 13]]

 [[11 12]
  [13 14]]

 [[12 13]
  [14 15]]

 [[13 14]
  [15 16]]

 [[14 15]
  [16 17]]

 [[15 16]
  [17 18]]

 [[16 17]
  [18 19]]

 [[17 18]
  [19 20]]

 [[18 19]
  [20 21]]

 [[19 20]
  [21 22]]

 [[20 21]
  [22 23]]

 [[21 22]
  [23 24]]

 [[22 23]
  [24 25]]

 [[23 24]
  [25 26]]

 [[24 25]
  [26 27]]

 [[25 26]
  [27 28]]

 [[26 27]
  [28 29]]

 [[27 28]
  [29 30]]

 [[28 29]
  [30 31]]

 [[29 30]
  [31 32]]

 [[30 31]
  [32 33]]

 [[31 32]
  [33 34]]

 [[32 33]
  [34 35]]

 [[33 34]
  [35 36]]

 [[34 35]
  [36 37]]

 [[35 36]
  [37 38]]

 [[36 37]
  [38 39]]

 [[37 38]
  [39 40]]

 [[38 39]
  [40 41]]

 [[39 40]
  [41 42]]

 [[40 41]
  [42 43]]

 [[41 42]
  [43 44]]

 [[42 43]
  [44 45]]

 [[43 44]
  [45 46]]

 [[44 45]
  [46 47]]

 [[45 46]
  [47 48]]


In [66]:
print(x.shape,y.shape)

(96, 2, 2) (96,)


In [67]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(
    x,y, shuffle = True,
    train_size=0.7,

    
)
print(x.shape,y.shape)


(96, 2, 2) (96,)


In [71]:
# RNN 모델구성 + 리턴시퀀스 적용
model = Sequential([
    Conv1D(128,kernel_size=2,input_shape=(2,2)),
    Dense(16,activation="relu"),
    Dense(1)
])

model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_18 (Conv1D)          (None, 1, 128)            640       
                                                                 
 dense_22 (Dense)            (None, 1, 16)             2064      
                                                                 
 dense_23 (Dense)            (None, 1, 1)              17        
                                                                 
Total params: 2,721
Trainable params: 2,721
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
67/67 [==============================] - 6s 3ms/step - loss: 11.7902
Epoch 2/100
67/67 [==============================] - 0s 2ms/step - loss: 7.2288
Epoch 3/100
67/67 [==============================] - 0s 2ms/step - loss: 5.0470
Epoch 4/100
67/67 [==============================] - 0s 2ms/step - loss: 5.3378
Epoch 5/100
67/67 [==============================] - 0s 2ms/step - loss: 5.3347
Epoch 6/100
67/67 [==============================] - 0s 3ms/step - loss: 5.0421
Epoch 7/100
67/67 [==============================] - 0s 2ms/step - loss: 4.9760
Epoch 8/100
67/67 [==============================] - 0s 2ms/step - loss: 4.0533
Epoch 9/100
67/67 [==============================] - 0s 3ms/step - loss: 4.1634
Epoch 10/100
67/67 [==============================] - 0s 2ms/step - loss: 5.1170
Epoch 11/100
67/67 [==============================] - 0s 2ms/step - loss: 3.9845
Epoch 12/100
67/67 [==============================] - 0s 3ms/step - loss: 4.5462
Epoch 13/100
67/67 [================

In [ ]:
loss = model.evaluate(x,y)

print(loss)

3/3 [==============================] - 0s 2ms/step - loss: 10.5934
10.59337329864502


In [ ]:
x_predict = np.array(range(96,106))
x_predict = split_x(x_predict,4)

# x_predict.shape
x_predict = x_predict.reshape(7,2,2)
print(x_predict.shape)
# (7,4) - > (7,4,1)
result = model.predict(x_predict)
print("결과 \n",result)

(7, 2, 2)
결과 
 [[[ 97.253   ]]

 [[ 98.22555 ]]

 [[ 99.198074]]

 [[100.170616]]

 [[101.14314 ]]

 [[102.115685]]

 [[103.08822 ]]]


In [ ]:
test = np.array([[[96, 97],[98, 99]]])

# print(test.shape)

result = model.predict(test)
print("결과",result)

결과 [[[97.253006]]]


In [ ]:
loss = model.evaluate(x_test,y_test)

print(loss)

1/1 [==============================] - 0s 141ms/step - loss: 28.9607
28.960681915283203
