In [5]:
# 파이썬 패키지 목록 확인하기
!pip freeze > requirements.txt


In [16]:
import tensorflow as tf
import numpy as np
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1" 
print(tf.__version__)
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

2.10.1


[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 7383912730419130035
 xla_global_id: -1]

In [8]:
a = np.array([[1,2],[3,4]])
print(a.shape)
a = np.array([[[1,2,3]]])
print(a.shape)
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
a = np.array([[[1],[2]]])
print(a.shape)
a = np.array([[1,2,3],[4,5]])
print(a.shape)


(2, 2)
(1, 1, 3)
(2, 3)
(1, 2, 1)
(2,)


C:\Users\bitcamp\AppData\Local\Temp\ipykernel_1496\444391095.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3],[4,5]])


In [10]:
arr = np.random.rand(10)

print(arr)

[0.03437988 0.37132459 0.69619231 0.30584578 0.44848634 0.29587775
 0.81044179 0.74577456 0.71335727 0.27760512]


In [24]:
import numpy as np
# print(np.random.normal(0,1,(1,3)))

# np.random.normal(0,1,(5,3,2))
# np.random.normal(0,1,(5,2))
# np.random.normal(0,1,(6,3,3))
# np.random.normal(0,1,(2,10))
# np.random.normal(0,1,(1,2,3,1))
# np.random.normal(0,1,(2,1,1,1,3))
# np.random.normal(0,1,(3,2))

for i in range(10):
    a= round(np.random.randint(1,4))
    b= round(np.random.randint(1,4))

    print(i+1 ,"번 ",np.random.randint(1,4,(a,b)))


1 번  [[2]
 [3]]
2 번  [[2 3 1]
 [3 2 2]
 [2 1 1]]
3 번  [[2 1]
 [3 1]
 [1 2]]
4 번  [[2 1]
 [1 2]
 [2 1]]
5 번  [[2 3 2]
 [2 1 2]]
6 번  [[2]
 [3]
 [1]]
7 번  [[2 2 1]
 [2 3 3]]
8 번  [[1]
 [2]]
9 번  [[2 3]
 [1 3]
 [1 1]]
10 번  [[2 2 3]
 [2 2 2]]


In [ ]:

a = np.array([[[[1]]]])
print(a.shape)

(1, 1, 1, 1)
