import numpy as np
from tensorflow.keras.models improt Sequential

In [46]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN

dataset = np.array([1,2,3,4,5,6,7])

In [47]:
x = np.array([[i,i+1,i+2] for i in dataset])
y = np.array([[i+3]for i in dataset])
print(x)
print(y)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [48]:
print(x.shape,y.shape)

(7, 3) (7, 1)


In [49]:
x = x.reshape(7,3,1)
x

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]],

       [[5],
        [6],
        [7]],

       [[6],
        [7],
        [8]],

       [[7],
        [8],
        [9]]])

In [50]:
print(x.shape,y.shape)

(7, 3, 1) (7, 1)


In [52]:
model = Sequential([
    SimpleRNN(64,input_shape=(3,1)),
    Dense(16,activation="relu"),
    Dense(1)
])

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_6 (SimpleRNN)    (None, 64)                4224      
                                                                 
 dense (Dense)               (None, 16)                1040      
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 5,281
Trainable params: 5,281
Non-trainable params: 0
_________________________________________________________________
