In [22]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU

a = np.array(range(1,101))
x_predict = np.array(range(96,106))



In [23]:
def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]

print(x,"\n",y)

(96, 5)
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]
 [22 23 24 25]
 [23 24 25 26]
 [24 25 26 27]
 [25 26 27 28]
 [26 27 28 29]
 [27 28 29 30]
 [28 29 30 31]
 [29 30 31 32]
 [30 31 32 33]
 [31 32 33 34]
 [32 33 34 35]
 [33 34 35 36]
 [34 35 36 37]
 [35 36 37 38]
 [36 37 38 39]
 [37 38 39 40]
 [38 39 40 41]
 [39 40 41 42]
 [40 41 42 43]
 [41 42 43 44]
 [42 43 44 45]
 [43 44 45 46]
 [44 45 46 47]
 [45 46 47 48]
 [46 47 48 49]
 [47 48 49 50]
 [48 49 50 51]
 [49 50 51 52]
 [50 51 52 53]
 [51 52 53 54]
 [52 53 54 55]
 [53 54 55 56]
 [54 55 56 57]
 [55 56 57 58]
 [56 57 58 59]
 [57 58 59 60]
 [58 59 60 61]
 [59 60 61 62]
 [60 61 62 63]
 [61 62 63 64]
 [62 63 64 65]
 [63 64 65 66]
 [64 65 66 67]
 [65 66 67 68]
 [66 67 68 69]
 [

In [24]:
print(x.shape,y.shape)

(96, 4) (96,)


In [25]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),4,1)
x

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[ 7],
        [ 8],
        [ 9],
        [10]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[10],
        [11],
        [12],
        [13]],

       [[11],
        [12],
        [13],
        [14]],

       [[12],
        [13],
        [14],
        [15]],

       [[13],
        [14],
        [15],
        [16]],

       [[14],
        [15],
        [16],
        [17]],

       [[15],
        [16],
        [17],
        [18]],

       [[16],
        [17],
        [18],
        [19]],

       [[17],
        [18],
        [19],
        [20]],

       [[18],


In [26]:
print(x.shape,y.shape)

(96, 4, 1) (96,)


In [27]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    # LSTM 은 3차원을 -> 2차원으로 변환함 flatten 필요없다
    # 따라서 LSTM 을 두번쓰면 오류발생
    
    GRU(32,input_shape=(4,1)),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_1 (GRU)                 (None, 32)                3360      
                                                                 
 dense_4 (Dense)             (None, 16)                528       
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 3,905
Trainable params: 3,905
Non-trainable params: 0
_________________________________________________________________


In [28]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
96/96 [==============================] - 1s 5ms/step - loss: 48.4140
Epoch 2/100
96/96 [==============================] - 0s 4ms/step - loss: 39.1985
Epoch 3/100
96/96 [==============================] - 0s 4ms/step - loss: 29.5652
Epoch 4/100
96/96 [==============================] - 0s 3ms/step - loss: 19.4620
Epoch 5/100
96/96 [==============================] - 0s 3ms/step - loss: 12.0978
Epoch 6/100
96/96 [==============================] - 0s 4ms/step - loss: 7.3917
Epoch 7/100
96/96 [==============================] - 0s 4ms/step - loss: 4.5008
Epoch 8/100
96/96 [==============================] - 0s 4ms/step - loss: 2.9585
Epoch 9/100
96/96 [==============================] - 0s 4ms/step - loss: 2.1569
Epoch 10/100
96/96 [==============================] - 0s 4ms/step - loss: 1.9422
Epoch 11/100
96/96 [==============================] - 0s 3ms/step - loss: 1.4952
Epoch 12/100
96/96 [==============================] - 0s 4ms/step - loss: 1.2463
Epoch 13/100
96/96 [============

In [29]:
loss = model.evaluate(x,y)

print(loss)



3/3 [==============================] - 0s 2ms/step - loss: 0.4987
0.4987269937992096


In [35]:
test = np.array([[[100],[101],[102],[103]]])
result = model.predict(test)
print("결과",result)

결과 [[101.51774]]
