In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU,Conv2D

a = np.array(range(1,11))

def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]
print(x,"\n",y)

(6, 5)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 [ 5  6  7  8  9 10]


In [3]:
print(x.shape,y.shape)

(6, 4) (6,)


In [4]:
# # 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
# x = x.reshape(len(x),4,1)
# x

In [5]:
print(x.shape,y.shape)

(6, 4) (6,)


In [6]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    # LSTM 은 3차원을 -> 2차원으로 변환함 flatten 필요없다
    # 따라서 LSTM 을 두번쓰면 오류발생
    
    Dense(64,input_shape=(4,)),
    Dense(32,activation="relu"),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                320       
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 16)                528       
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 2,945
Trainable params: 2,945
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
6/6 [==============================] - 1s 2ms/step - loss: 6.9921
Epoch 2/100
6/6 [==============================] - 0s 2ms/step - loss: 6.0666
Epoch 3/100
6/6 [==============================] - 0s 2ms/step - loss: 5.3754
Epoch 4/100
6/6 [==============================] - 0s 2ms/step - loss: 4.6108
Epoch 5/100
6/6 [==============================] - 0s 2ms/step - loss: 3.5645
Epoch 6/100
6/6 [==============================] - 0s 2ms/step - loss: 2.4819
Epoch 7/100
6/6 [==============================] - 0s 3ms/step - loss: 1.0005
Epoch 8/100
6/6 [==============================] - 0s 2ms/step - loss: 0.9123
Epoch 9/100
6/6 [==============================] - 0s 2ms/step - loss: 1.1913
Epoch 10/100
6/6 [==============================] - 0s 2ms/step - loss: 0.7052
Epoch 11/100
6/6 [==============================] - 0s 2ms/step - loss: 0.8195
Epoch 12/100
6/6 [==============================] - 0s 2ms/step - loss: 0.9646
Epoch 13/100
6/6 [==============================] - 0s 2ms/st

In [8]:
loss = model.evaluate(x,y)
print(loss)

1/1 [==============================] - 0s 87ms/step - loss: 0.0233
0.02331145666539669


In [9]:
test = np.array([[7,8,9,10]])
result = model.predict(test)
print("결과",result)

결과 [[10.946227]]
