In [4]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU,Dropout
from tensorflow.keras.datasets import mnist
# 이미 훈련과 테스트가 분리된 데이터임
(x_train,y_train),(x_test,y_test) = mnist.load_data()



(60000, 28, 28) (60000,)


In [6]:
def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(x_train,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]

print(x,"\n",y)
print(x_train.shape,y_train.shape)

(59996, 5, 28, 28)
[[[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]


 [[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ...

In [24]:
print(x.shape,y.shape)

(96, 4) (96,)


In [25]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),2,2,1)
print(x.shape)
print(x)

(96, 2, 2, 1)
[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]]


 [[[ 2]
   [ 3]]

  [[ 4]
   [ 5]]]


 [[[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 4]
   [ 5]]

  [[ 6]
   [ 7]]]


 [[[ 5]
   [ 6]]

  [[ 7]
   [ 8]]]


 [[[ 6]
   [ 7]]

  [[ 8]
   [ 9]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]]


 [[[ 8]
   [ 9]]

  [[10]
   [11]]]


 [[[ 9]
   [10]]

  [[11]
   [12]]]


 [[[10]
   [11]]

  [[12]
   [13]]]


 [[[11]
   [12]]

  [[13]
   [14]]]


 [[[12]
   [13]]

  [[14]
   [15]]]


 [[[13]
   [14]]

  [[15]
   [16]]]


 [[[14]
   [15]]

  [[16]
   [17]]]


 [[[15]
   [16]]

  [[17]
   [18]]]


 [[[16]
   [17]]

  [[18]
   [19]]]


 [[[17]
   [18]]

  [[19]
   [20]]]


 [[[18]
   [19]]

  [[20]
   [21]]]


 [[[19]
   [20]]

  [[21]
   [22]]]


 [[[20]
   [21]]

  [[22]
   [23]]]


 [[[21]
   [22]]

  [[23]
   [24]]]


 [[[22]
   [23]]

  [[24]
   [25]]]


 [[[23]
   [24]]

  [[25]
   [26]]]


 [[[24]
   [25]]

  [[26]
   [27]]]


 [[[25]
   [26]]

  [[27]
   [28]]]


 [[[26]
   [27]]

  [[28]
   [29]]]


In [26]:
print(x.shape,y.shape)

(96, 2, 2, 1) (96,)


In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(
    x,y, shuffle = True,
    train_size=0.7,

    
)
print(x.shape,y.shape)


(96, 2, 2, 1) (96,)


In [28]:
# 모델
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,Conv2D,MaxPooling2D,Flatten

# 모델
rate = 0.2
model = Sequential([
    # 5X5 이미지 채널 1개 
    # 필터 = output 노드수 
    # 자르는 필터는 2X2 사이즈 
    Conv2D(filters=64,kernel_size=(2,1),input_shape=(2,2,1),activation="relu"),

    Flatten(),
    Dense(16,activation="relu"),
    Dense(1,activation="linear")
])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 1, 2, 64)          192       
                                                                 
 flatten_1 (Flatten)         (None, 128)               0         
                                                                 
 dense_4 (Dense)             (None, 16)                2064      
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 2,273
Trainable params: 2,273
Non-trainable params: 0
_________________________________________________________________


In [29]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
67/67 [==============================] - 8s 3ms/step - loss: 28.1425
Epoch 2/100
67/67 [==============================] - 0s 3ms/step - loss: 1.9049
Epoch 3/100
67/67 [==============================] - 0s 3ms/step - loss: 1.0960
Epoch 4/100
67/67 [==============================] - 0s 2ms/step - loss: 1.0305
Epoch 5/100
67/67 [==============================] - 0s 3ms/step - loss: 0.9376
Epoch 6/100
67/67 [==============================] - 0s 3ms/step - loss: 1.0976
Epoch 7/100
67/67 [==============================] - 0s 3ms/step - loss: 0.9902
Epoch 8/100
67/67 [==============================] - 0s 3ms/step - loss: 0.8330
Epoch 9/100
67/67 [==============================] - 0s 3ms/step - loss: 0.9291
Epoch 10/100
67/67 [==============================] - 0s 2ms/step - loss: 0.8619
Epoch 11/100
67/67 [==============================] - 0s 2ms/step - loss: 0.6269
Epoch 12/100
67/67 [==============================] - 0s 3ms/step - loss: 0.5493
Epoch 13/100
67/67 [================

In [30]:
loss = model.evaluate(x,y)

print(loss)

3/3 [==============================] - 0s 3ms/step - loss: 0.0704
0.07038578391075134


In [31]:
x_predict = np.array(range(96,106))
x_predict = split_x(x_predict,4)
# x_predict.shape
x_predict = x_predict.reshape(7,2,2,1)
x_predict.shape
# (7,4) - > (7,4,1)
result = model.predict(x_predict)
print("결과 \n",result)

결과 
 [[100.145905]
 [101.1475  ]
 [102.14909 ]
 [103.150696]
 [104.1523  ]
 [105.153885]
 [106.15549 ]]


In [32]:
# test = np.array([[[96, 97],[98, 99]]])

# # print(test.shape)

# result = model.predict(test)
# print("결과",result)

In [33]:
loss = model.evaluate(x_test,y_test)

print(loss)



1/1 [==============================] - 0s 188ms/step - loss: 0.0716
0.07155311852693558
