import numpy as np
from tensorflow.keras.models improt Sequential

In [303]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN

dataset = np.array([1,2,3,4,5,6,7])

In [304]:
x = np.array([[i,i+1,i+2] for i in dataset])
y = np.array([i+3 for i in dataset])

x = np.array([
 [1 ,2 ,3],
 [2 ,3 ,4],
 [3 ,4 ,5],
 [4 ,5 ,6],
 [5 ,6 ,7],
 [6 ,7 ,8],
 [7 ,8 ,9]])
y = np.array([4,5,6,7,8,9,10])



print(x)
print(y)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[ 4  5  6  7  8  9 10]


In [305]:
print(x.shape,y.shape)

(7, 3) (7,)


In [306]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(7,3,1)
x

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]],

       [[5],
        [6],
        [7]],

       [[6],
        [7],
        [8]],

       [[7],
        [8],
        [9]]])

In [307]:
print(x.shape,y.shape)

(7, 3, 1) (7,)


In [312]:
# RNN모델구성
model = Sequential([
    # input_shape 는 행 무시 
    SimpleRNN(64,input_shape=(3,1)),
    Dense(16,activation="relu"),
    Dense(1)
])

model.summary()

Model: "sequential_33"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_33 (SimpleRNN)   (None, 64)                4224      
                                                                 
 dense_54 (Dense)            (None, 16)                1040      
                                                                 
 dense_55 (Dense)            (None, 1)                 17        
                                                                 
Total params: 5,281
Trainable params: 5,281
Non-trainable params: 0
_________________________________________________________________


In [309]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
7/7 [==============================] - 0s 4ms/step - loss: 7.2923
Epoch 2/100
7/7 [==============================] - 0s 4ms/step - loss: 6.1849
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 5.6013
Epoch 4/100
7/7 [==============================] - 0s 4ms/step - loss: 5.1013
Epoch 5/100
7/7 [==============================] - 0s 4ms/step - loss: 4.5469
Epoch 6/100
7/7 [==============================] - 0s 4ms/step - loss: 3.9758
Epoch 7/100
7/7 [==============================] - 0s 4ms/step - loss: 3.3841
Epoch 8/100
7/7 [==============================] - 0s 4ms/step - loss: 2.7787
Epoch 9/100
7/7 [==============================] - 0s 4ms/step - loss: 2.3397
Epoch 10/100
7/7 [==============================] - 0s 4ms/step - loss: 1.9704
Epoch 11/100
7/7 [==============================] - 0s 4ms/step - loss: 1.8240
Epoch 12/100
7/7 [==============================] - 0s 4ms/step - loss: 1.6711
Epoch 13/100
7/7 [==============================] - 0s 4ms/st

In [310]:
loss = model.evaluate(x,y)

print(loss)



1/1 [==============================] - 0s 126ms/step - loss: 0.0477
0.04773541912436485


In [311]:
test = np.array([[[8],[9],[10]]])
result = model.predict(test)
print("[[8],[9],[10]]의 결과",result)

[[8],[9],[10]]의 결과 [[10.558087]]
