import numpy as np
from tensorflow.keras.models improt Sequential

In [12]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM

dataset = np.array([1,2,3,4,5,6,7])

In [13]:
x = np.array([[i,i+1,i+2] for i in dataset])
y = np.array([i+3 for i in dataset])

# x = np.array([
#  [1 ,2 ,3],
#  [2 ,3 ,4],
#  [3 ,4 ,5],
#  [4 ,5 ,6],
#  [5 ,6 ,7],
#  [6 ,7 ,8],
#  [7 ,8 ,9]])
# y = np.array([4,5,6,7,8,9,10])



print(x)
print(y)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[ 4  5  6  7  8  9 10]


In [14]:
print(x.shape,y.shape)

(7, 3) (7,)


In [15]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(7,3,1)
x

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]],

       [[5],
        [6],
        [7]],

       [[6],
        [7],
        [8]],

       [[7],
        [8],
        [9]]])

In [16]:
print(x.shape,y.shape)

(7, 3, 1) (7,)


In [17]:

# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    LSTM(64,input_shape=(3,1)),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 64)                16896     
                                                                 
 dense_4 (Dense)             (None, 16)                1040      
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 17,953
Trainable params: 17,953
Non-trainable params: 0
_________________________________________________________________


In [18]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
7/7 [==============================] - 1s 4ms/step - loss: 7.0742
Epoch 2/100
7/7 [==============================] - 0s 4ms/step - loss: 6.8423
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 6.5565
Epoch 4/100
7/7 [==============================] - 0s 4ms/step - loss: 6.2345
Epoch 5/100
7/7 [==============================] - 0s 4ms/step - loss: 5.8356
Epoch 6/100
7/7 [==============================] - 0s 4ms/step - loss: 5.3353
Epoch 7/100
7/7 [==============================] - 0s 4ms/step - loss: 4.7170
Epoch 8/100
7/7 [==============================] - 0s 4ms/step - loss: 3.9795
Epoch 9/100
7/7 [==============================] - 0s 4ms/step - loss: 2.9526
Epoch 10/100
7/7 [==============================] - 0s 4ms/step - loss: 1.7697
Epoch 11/100
7/7 [==============================] - 0s 4ms/step - loss: 0.9065
Epoch 12/100
7/7 [==============================] - 0s 4ms/step - loss: 0.8880
Epoch 13/100
7/7 [==============================] - 0s 4ms/st

In [19]:
loss = model.evaluate(x,y)

print(loss)



1/1 [==============================] - 0s 304ms/step - loss: 0.0686
0.06860657781362534


In [20]:
test = np.array([[[8],[9],[10]]])
result = model.predict(test)
print("[[8],[9],[10]]의 결과",result)

[[8],[9],[10]]의 결과 [[10.73745]]
