In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU,Dropout,Bidirectional


a = np.array(range(1,101))
x_predict = np.array(range(96,106))



In [3]:
def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]

print(x,"\n",y)

(96, 5)
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]
 [22 23 24 25]
 [23 24 25 26]
 [24 25 26 27]
 [25 26 27 28]
 [26 27 28 29]
 [27 28 29 30]
 [28 29 30 31]
 [29 30 31 32]
 [30 31 32 33]
 [31 32 33 34]
 [32 33 34 35]
 [33 34 35 36]
 [34 35 36 37]
 [35 36 37 38]
 [36 37 38 39]
 [37 38 39 40]
 [38 39 40 41]
 [39 40 41 42]
 [40 41 42 43]
 [41 42 43 44]
 [42 43 44 45]
 [43 44 45 46]
 [44 45 46 47]
 [45 46 47 48]
 [46 47 48 49]
 [47 48 49 50]
 [48 49 50 51]
 [49 50 51 52]
 [50 51 52 53]
 [51 52 53 54]
 [52 53 54 55]
 [53 54 55 56]
 [54 55 56 57]
 [55 56 57 58]
 [56 57 58 59]
 [57 58 59 60]
 [58 59 60 61]
 [59 60 61 62]
 [60 61 62 63]
 [61 62 63 64]
 [62 63 64 65]
 [63 64 65 66]
 [64 65 66 67]
 [65 66 67 68]
 [66 67 68 69]
 [

In [4]:
print(x.shape,y.shape)

(96, 4) (96,)


In [5]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),2,2)
print(x.shape)
print(x)

(96, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 2  3]
  [ 4  5]]

 [[ 3  4]
  [ 5  6]]

 [[ 4  5]
  [ 6  7]]

 [[ 5  6]
  [ 7  8]]

 [[ 6  7]
  [ 8  9]]

 [[ 7  8]
  [ 9 10]]

 [[ 8  9]
  [10 11]]

 [[ 9 10]
  [11 12]]

 [[10 11]
  [12 13]]

 [[11 12]
  [13 14]]

 [[12 13]
  [14 15]]

 [[13 14]
  [15 16]]

 [[14 15]
  [16 17]]

 [[15 16]
  [17 18]]

 [[16 17]
  [18 19]]

 [[17 18]
  [19 20]]

 [[18 19]
  [20 21]]

 [[19 20]
  [21 22]]

 [[20 21]
  [22 23]]

 [[21 22]
  [23 24]]

 [[22 23]
  [24 25]]

 [[23 24]
  [25 26]]

 [[24 25]
  [26 27]]

 [[25 26]
  [27 28]]

 [[26 27]
  [28 29]]

 [[27 28]
  [29 30]]

 [[28 29]
  [30 31]]

 [[29 30]
  [31 32]]

 [[30 31]
  [32 33]]

 [[31 32]
  [33 34]]

 [[32 33]
  [34 35]]

 [[33 34]
  [35 36]]

 [[34 35]
  [36 37]]

 [[35 36]
  [37 38]]

 [[36 37]
  [38 39]]

 [[37 38]
  [39 40]]

 [[38 39]
  [40 41]]

 [[39 40]
  [41 42]]

 [[40 41]
  [42 43]]

 [[41 42]
  [43 44]]

 [[42 43]
  [44 45]]

 [[43 44]
  [45 46]]

 [[44 45]
  [46 47]]

 [[45 46]
  [47 48]]


In [6]:
print(x.shape,y.shape)

(96, 2, 2) (96,)


In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(
    x,y, shuffle = True,
    train_size=0.7,

    
)
print(x.shape,y.shape)


(96, 2, 2) (96,)


In [8]:
# RNN 모델구성 + 리턴시퀀스 적용
model = Sequential([
    Bidirectional(LSTM(64,return_sequences=True),input_shape=(2,2),),
    # Bidirectional 을 사용하면 일반 LSTM 에 비해 연상량이 2배 증가합니다.
    LSTM(32),
    Dropout(0.2),
    Dense(16,activation="relu"),
    Dense(1)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirectiona  (None, 2, 128)           34304     
 l)                                                              
                                                                 
 lstm_1 (LSTM)               (None, 32)                20608     
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 16)                528       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 55,457
Trainable params: 55,457
Non-trainable params: 0
____________________________________________________

In [9]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
67/67 [==============================] - 12s 22ms/step - loss: 48.5803
Epoch 2/100
67/67 [==============================] - 1s 12ms/step - loss: 42.6873
Epoch 3/100
67/67 [==============================] - 1s 17ms/step - loss: 37.1490
Epoch 4/100
67/67 [==============================] - 1s 13ms/step - loss: 32.6193
Epoch 5/100
67/67 [==============================] - 1s 11ms/step - loss: 26.1048
Epoch 6/100
67/67 [==============================] - 2s 28ms/step - loss: 21.1043
Epoch 7/100
67/67 [==============================] - 3s 51ms/step - loss: 17.5833
Epoch 8/100
67/67 [==============================] - 3s 42ms/step - loss: 15.2857
Epoch 9/100
67/67 [==============================] - 2s 23ms/step - loss: 11.4474
Epoch 10/100
67/67 [==============================] - 2s 24ms/step - loss: 9.9004
Epoch 11/100
67/67 [==============================] - 1s 18ms/step - loss: 9.3330
Epoch 12/100
67/67 [==============================] - 1s 15ms/step - loss: 7.8273
Epoch 13/100
67

In [10]:
loss = model.evaluate(x,y)

print(loss)

3/3 [==============================] - 1s 5ms/step - loss: 1.1016
1.1015502214431763


In [14]:
x_predict = np.array(range(96,106))
x_predict = split_x(x_predict,4)
# x_predict.shape
x_predict = x_predict.reshape(7,2,2)
x_predict.shape
# (7,4) - > (7,4,1)
result = model.predict(x_predict)
print("결과 \n",result)

ValueError: cannot reshape array of size 18 into shape (7,2,2)

In [12]:
test = np.array([[[96, 97],[98, 99]]])

# print(test.shape)

result = model.predict(test)
print("결과",result)

결과 [[93.04006]]


In [13]:
loss = model.evaluate(x_test,y_test)

print(loss)

1/1 [==============================] - 1s 788ms/step - loss: 1.0932
1.0931711196899414
