In [14]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU,Dropout

a = np.array(range(1,101))
x_predict = np.array(range(96,106))



In [15]:
def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]

print(x,"\n",y)

(96, 5)
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]
 [22 23 24 25]
 [23 24 25 26]
 [24 25 26 27]
 [25 26 27 28]
 [26 27 28 29]
 [27 28 29 30]
 [28 29 30 31]
 [29 30 31 32]
 [30 31 32 33]
 [31 32 33 34]
 [32 33 34 35]
 [33 34 35 36]
 [34 35 36 37]
 [35 36 37 38]
 [36 37 38 39]
 [37 38 39 40]
 [38 39 40 41]
 [39 40 41 42]
 [40 41 42 43]
 [41 42 43 44]
 [42 43 44 45]
 [43 44 45 46]
 [44 45 46 47]
 [45 46 47 48]
 [46 47 48 49]
 [47 48 49 50]
 [48 49 50 51]
 [49 50 51 52]
 [50 51 52 53]
 [51 52 53 54]
 [52 53 54 55]
 [53 54 55 56]
 [54 55 56 57]
 [55 56 57 58]
 [56 57 58 59]
 [57 58 59 60]
 [58 59 60 61]
 [59 60 61 62]
 [60 61 62 63]
 [61 62 63 64]
 [62 63 64 65]
 [63 64 65 66]
 [64 65 66 67]
 [65 66 67 68]
 [66 67 68 69]
 [

In [16]:
print(x.shape,y.shape)

(96, 4) (96,)


In [17]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),2,2,1)
print(x.shape)
print(x)

(96, 2, 2, 1)
[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]]


 [[[ 2]
   [ 3]]

  [[ 4]
   [ 5]]]


 [[[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 4]
   [ 5]]

  [[ 6]
   [ 7]]]


 [[[ 5]
   [ 6]]

  [[ 7]
   [ 8]]]


 [[[ 6]
   [ 7]]

  [[ 8]
   [ 9]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]]


 [[[ 8]
   [ 9]]

  [[10]
   [11]]]


 [[[ 9]
   [10]]

  [[11]
   [12]]]


 [[[10]
   [11]]

  [[12]
   [13]]]


 [[[11]
   [12]]

  [[13]
   [14]]]


 [[[12]
   [13]]

  [[14]
   [15]]]


 [[[13]
   [14]]

  [[15]
   [16]]]


 [[[14]
   [15]]

  [[16]
   [17]]]


 [[[15]
   [16]]

  [[17]
   [18]]]


 [[[16]
   [17]]

  [[18]
   [19]]]


 [[[17]
   [18]]

  [[19]
   [20]]]


 [[[18]
   [19]]

  [[20]
   [21]]]


 [[[19]
   [20]]

  [[21]
   [22]]]


 [[[20]
   [21]]

  [[22]
   [23]]]


 [[[21]
   [22]]

  [[23]
   [24]]]


 [[[22]
   [23]]

  [[24]
   [25]]]


 [[[23]
   [24]]

  [[25]
   [26]]]


 [[[24]
   [25]]

  [[26]
   [27]]]


 [[[25]
   [26]]

  [[27]
   [28]]]


 [[[26]
   [27]]

  [[28]
   [29]]]


In [18]:
print(x.shape,y.shape)

(96, 2, 2, 1) (96,)


In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(
    x,y, shuffle = True,
    train_size=0.7,

    
)
print(x.shape,y.shape)


(96, 2, 2, 1) (96,)


In [20]:
# 모델
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,Conv2D,MaxPooling2D,Flatten

# 모델
rate = 0.2
model = Sequential([
    # 5X5 이미지 채널 1개 
    # 필터 = output 노드수 
    # 자르는 필터는 2X2 사이즈 
    Conv2D(filters=64,kernel_size=(2,1),input_shape=(2,2,1),activation="relu"),

    Flatten(),
    Dense(16,activation="relu"),
    Dense(1,activation="linear")
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 1, 1, 64)          192       
                                                                 
 flatten (Flatten)           (None, 64)                0         
                                                                 
 dense_2 (Dense)             (None, 16)                1040      
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 1,249
Trainable params: 1,249
Non-trainable params: 0
_________________________________________________________________


In [21]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100


ValueError: in user code:

    File "c:\Users\bitcamp\anaconda3\envs\tf274gpu\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\bitcamp\anaconda3\envs\tf274gpu\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\bitcamp\anaconda3\envs\tf274gpu\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\bitcamp\anaconda3\envs\tf274gpu\lib\site-packages\keras\engine\training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\bitcamp\anaconda3\envs\tf274gpu\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\bitcamp\anaconda3\envs\tf274gpu\lib\site-packages\keras\engine\input_spec.py", line 263, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_1" is incompatible with the layer: expected shape=(None, 2, 1, 1), found shape=(1, 2, 2, 1)


In [ ]:
loss = model.evaluate(x,y)

print(loss)

3/3 [==============================] - 0s 2ms/step - loss: 1.7809
1.7808579206466675


In [ ]:
x_predict = np.array(range(96,106))
x_predict = split_x(x_predict,4)
# x_predict.shape
x_predict = x_predict.reshape(7,2,2,1)
x_predict.shape
# (7,4) - > (7,4,1)
result = model.predict(x_predict)
print("결과 \n",result)

결과 
 [[96.07077]
 [96.41861]
 [96.74991]
 [97.06546]
 [97.36604]
 [97.65241]
 [97.92529]]


In [ ]:
# test = np.array([[[96, 97],[98, 99]]])

# # print(test.shape)

# result = model.predict(test)
# print("결과",result)

결과 [[96.07077]]


In [ ]:
loss = model.evaluate(x_test,y_test)

print(loss)



1/1 [==============================] - 0s 298ms/step - loss: 1.6122
1.6122257709503174
