In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU

dataset = np.array([1,2,3,4,5,6,7])

In [3]:
# x = np.array([[i,i+1,i+2] for i in dataset])
# y = np.array([i+3 for i in dataset])

x = np.array([
 [1 ,2 ,3],
 [2 ,3 ,4],
 [3 ,4 ,5],
 [4 ,5 ,6],
 [5 ,6 ,7],
 [6 ,7 ,8],
 [7 ,8 ,9],
 [8,9,10],
 [20,30,40],
 [30,40,50],
 [40,50,60]])

y = np.array([4,5,6,7,8,9,10,11,50,60,70])



print(x)
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [20 30 40]
 [30 40 50]
 [40 50 60]]
[ 4  5  6  7  8  9 10 11 50 60 70]


In [4]:
print(x.shape,y.shape)

(11, 3) (11,)


In [5]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),3,1)
x

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]]])

In [6]:
print(x.shape,y.shape)

(11, 3, 1) (11,)


In [11]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    # LSTM 은 3차원을 -> 2차원으로 변환함 flatten 필요없다
    # 따라서 LSTM 을 두번쓰면 오류발생
    LSTM(128,input_shape=(3,1)),
    LSTM(64),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

ValueError: Input 0 of layer "lstm_2" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 128)

In [8]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
11/11 [==============================] - 3s 4ms/step - loss: 21.1435
Epoch 2/100
11/11 [==============================] - 0s 4ms/step - loss: 19.9417
Epoch 3/100
11/11 [==============================] - 0s 4ms/step - loss: 18.1870
Epoch 4/100
11/11 [==============================] - 0s 4ms/step - loss: 15.5293
Epoch 5/100
11/11 [==============================] - 0s 4ms/step - loss: 14.7289
Epoch 6/100
11/11 [==============================] - 0s 4ms/step - loss: 14.0070
Epoch 7/100
11/11 [==============================] - 0s 4ms/step - loss: 13.5726
Epoch 8/100
11/11 [==============================] - 0s 4ms/step - loss: 13.3487
Epoch 9/100
11/11 [==============================] - 0s 4ms/step - loss: 13.1801
Epoch 10/100
11/11 [==============================] - 0s 4ms/step - loss: 12.7978
Epoch 11/100
11/11 [==============================] - 0s 4ms/step - loss: 12.6226
Epoch 12/100
11/11 [==============================] - 0s 4ms/step - loss: 12.2842
Epoch 13/100
11/11 [=====

In [9]:
loss = model.evaluate(x,y)

print(loss)



1/1 [==============================] - 0s 377ms/step - loss: 0.6528
0.6527840495109558


In [10]:
test = np.array([[[50],[60],[70]]])
result = model.predict(test)
print("결과",result)

결과 [[72.53444]]
