In [46]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU,Dropout

a = np.array(range(1,101))
x_predict = np.array(range(96,106))



In [47]:
def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]

print(x,"\n",y)

(96, 5)
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]
 [22 23 24 25]
 [23 24 25 26]
 [24 25 26 27]
 [25 26 27 28]
 [26 27 28 29]
 [27 28 29 30]
 [28 29 30 31]
 [29 30 31 32]
 [30 31 32 33]
 [31 32 33 34]
 [32 33 34 35]
 [33 34 35 36]
 [34 35 36 37]
 [35 36 37 38]
 [36 37 38 39]
 [37 38 39 40]
 [38 39 40 41]
 [39 40 41 42]
 [40 41 42 43]
 [41 42 43 44]
 [42 43 44 45]
 [43 44 45 46]
 [44 45 46 47]
 [45 46 47 48]
 [46 47 48 49]
 [47 48 49 50]
 [48 49 50 51]
 [49 50 51 52]
 [50 51 52 53]
 [51 52 53 54]
 [52 53 54 55]
 [53 54 55 56]
 [54 55 56 57]
 [55 56 57 58]
 [56 57 58 59]
 [57 58 59 60]
 [58 59 60 61]
 [59 60 61 62]
 [60 61 62 63]
 [61 62 63 64]
 [62 63 64 65]
 [63 64 65 66]
 [64 65 66 67]
 [65 66 67 68]
 [66 67 68 69]
 [

In [48]:
print(x.shape,y.shape)

(96, 4) (96,)


In [49]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),2,2)
print(x.shape)
print(x)

(96, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 2  3]
  [ 4  5]]

 [[ 3  4]
  [ 5  6]]

 [[ 4  5]
  [ 6  7]]

 [[ 5  6]
  [ 7  8]]

 [[ 6  7]
  [ 8  9]]

 [[ 7  8]
  [ 9 10]]

 [[ 8  9]
  [10 11]]

 [[ 9 10]
  [11 12]]

 [[10 11]
  [12 13]]

 [[11 12]
  [13 14]]

 [[12 13]
  [14 15]]

 [[13 14]
  [15 16]]

 [[14 15]
  [16 17]]

 [[15 16]
  [17 18]]

 [[16 17]
  [18 19]]

 [[17 18]
  [19 20]]

 [[18 19]
  [20 21]]

 [[19 20]
  [21 22]]

 [[20 21]
  [22 23]]

 [[21 22]
  [23 24]]

 [[22 23]
  [24 25]]

 [[23 24]
  [25 26]]

 [[24 25]
  [26 27]]

 [[25 26]
  [27 28]]

 [[26 27]
  [28 29]]

 [[27 28]
  [29 30]]

 [[28 29]
  [30 31]]

 [[29 30]
  [31 32]]

 [[30 31]
  [32 33]]

 [[31 32]
  [33 34]]

 [[32 33]
  [34 35]]

 [[33 34]
  [35 36]]

 [[34 35]
  [36 37]]

 [[35 36]
  [37 38]]

 [[36 37]
  [38 39]]

 [[37 38]
  [39 40]]

 [[38 39]
  [40 41]]

 [[39 40]
  [41 42]]

 [[40 41]
  [42 43]]

 [[41 42]
  [43 44]]

 [[42 43]
  [44 45]]

 [[43 44]
  [45 46]]

 [[44 45]
  [46 47]]

 [[45 46]
  [47 48]]


In [50]:
print(x.shape,y.shape)

(96, 2, 2) (96,)


In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(
    x,y, shuffle = True,
    train_size=0.7,

    
)
print(x.shape,y.shape)


(96, 2, 2) (96,)


In [52]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    # LSTM 은 3차원을 -> 2차원으로 변환함 flatten 필요없다
    # 따라서 LSTM 을 두번쓰면 오류발생
    LSTM(64,input_shape=(2,2)),

    Dropout(0.2),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 64)                17152     
                                                                 
 dropout_4 (Dropout)         (None, 64)                0         
                                                                 
 dense_8 (Dense)             (None, 16)                1040      
                                                                 
 dense_9 (Dense)             (None, 1)                 17        
                                                                 
Total params: 18,209
Trainable params: 18,209
Non-trainable params: 0
_________________________________________________________________


In [53]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
67/67 [==============================] - 1s 4ms/step - loss: 47.7310
Epoch 2/100
67/67 [==============================] - 0s 4ms/step - loss: 37.1621
Epoch 3/100
67/67 [==============================] - 0s 4ms/step - loss: 25.6220
Epoch 4/100
67/67 [==============================] - 0s 3ms/step - loss: 18.5402
Epoch 5/100
67/67 [==============================] - 0s 3ms/step - loss: 14.3703
Epoch 6/100
67/67 [==============================] - 0s 3ms/step - loss: 10.2277
Epoch 7/100
67/67 [==============================] - 0s 4ms/step - loss: 7.8563
Epoch 8/100
67/67 [==============================] - 0s 3ms/step - loss: 6.2360
Epoch 9/100
67/67 [==============================] - 0s 3ms/step - loss: 6.4268
Epoch 10/100
67/67 [==============================] - 0s 3ms/step - loss: 4.6551
Epoch 11/100
67/67 [==============================] - 0s 3ms/step - loss: 4.2530
Epoch 12/100
67/67 [==============================] - 0s 3ms/step - loss: 4.6754
Epoch 13/100
67/67 [===========

In [54]:
loss = model.evaluate(x,y)

print(loss)

3/3 [==============================] - 0s 4ms/step - loss: 1.6461
1.6461315155029297


In [55]:
x_predict = np.array(range(96,106))
x_predict = split_x(x_predict,4)
# x_predict.shape
x_predict = x_predict.reshape(7,2,2)
x_predict.shape
# (7,4) - > (7,4,1)
result = model.predict(x_predict)
print("결과 \n",result)

결과 
 [[92.572655]
 [92.98077 ]
 [93.370865]
 [93.74377 ]
 [94.10029 ]
 [94.441185]
 [94.76725 ]]


In [56]:
test = np.array([[[96, 97],[98, 99]]])

# print(test.shape)

result = model.predict(test)
print("결과",result)

결과 [[92.57266]]


In [57]:
loss = model.evaluate(x_test,y_test)

print(loss)



1/1 [==============================] - 0s 313ms/step - loss: 1.6558
1.6558291912078857
