In [140]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU,Dropout

a = np.array(range(1,101))
x_predict = np.array(range(96,106))



In [141]:
def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]

print(x,"\n",y)

(96, 5)
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]
 [22 23 24 25]
 [23 24 25 26]
 [24 25 26 27]
 [25 26 27 28]
 [26 27 28 29]
 [27 28 29 30]
 [28 29 30 31]
 [29 30 31 32]
 [30 31 32 33]
 [31 32 33 34]
 [32 33 34 35]
 [33 34 35 36]
 [34 35 36 37]
 [35 36 37 38]
 [36 37 38 39]
 [37 38 39 40]
 [38 39 40 41]
 [39 40 41 42]
 [40 41 42 43]
 [41 42 43 44]
 [42 43 44 45]
 [43 44 45 46]
 [44 45 46 47]
 [45 46 47 48]
 [46 47 48 49]
 [47 48 49 50]
 [48 49 50 51]
 [49 50 51 52]
 [50 51 52 53]
 [51 52 53 54]
 [52 53 54 55]
 [53 54 55 56]
 [54 55 56 57]
 [55 56 57 58]
 [56 57 58 59]
 [57 58 59 60]
 [58 59 60 61]
 [59 60 61 62]
 [60 61 62 63]
 [61 62 63 64]
 [62 63 64 65]
 [63 64 65 66]
 [64 65 66 67]
 [65 66 67 68]
 [66 67 68 69]
 [

In [142]:
print(x.shape,y.shape)

(96, 4) (96,)


In [143]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),4,1)
x.shape

(96, 4, 1)

In [144]:
print(x.shape,y.shape)

(96, 4, 1) (96,)


In [145]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(
    x,y, shuffle = True,
    train_size=0.7,

    
)

In [146]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    # LSTM 은 3차원을 -> 2차원으로 변환함 flatten 필요없다
    # 따라서 LSTM 을 두번쓰면 오류발생
    GRU(64,input_shape=(4,1),return_sequences=True),
    GRU(32,input_shape=(4,1)),
    Dropout(0.2),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_7 (GRU)                 (None, 4, 64)             12864     
                                                                 
 gru_8 (GRU)                 (None, 32)                9408      
                                                                 
 dropout_3 (Dropout)         (None, 32)                0         
                                                                 
 dense_16 (Dense)            (None, 16)                528       
                                                                 
 dense_17 (Dense)            (None, 1)                 17        
                                                                 
Total params: 22,817
Trainable params: 22,817
Non-trainable params: 0
_________________________________________________________________


In [147]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
67/67 [==============================] - 2s 5ms/step - loss: 50.4790
Epoch 2/100
67/67 [==============================] - 0s 5ms/step - loss: 42.0941
Epoch 3/100
67/67 [==============================] - 0s 5ms/step - loss: 34.8641
Epoch 4/100
67/67 [==============================] - 0s 4ms/step - loss: 26.7644
Epoch 5/100
67/67 [==============================] - 0s 5ms/step - loss: 20.2359
Epoch 6/100
67/67 [==============================] - 0s 5ms/step - loss: 13.9854
Epoch 7/100
67/67 [==============================] - 0s 4ms/step - loss: 13.0844
Epoch 8/100
67/67 [==============================] - 0s 5ms/step - loss: 10.1016
Epoch 9/100
67/67 [==============================] - 0s 4ms/step - loss: 7.0444
Epoch 10/100
67/67 [==============================] - 0s 4ms/step - loss: 8.2316
Epoch 11/100
67/67 [==============================] - 0s 4ms/step - loss: 5.4865
Epoch 12/100
67/67 [==============================] - 0s 4ms/step - loss: 7.0098
Epoch 13/100
67/67 [=========

In [148]:
loss = model.evaluate(x,y)

print(loss)

3/3 [==============================] - 1s 2ms/step - loss: 1.0977
1.0977457761764526


In [149]:
x_predict = np.array(range(96,106))
x_predict = split_x(x_predict,4)
# x_predict.shape
x_predict = x_predict.reshape(7,4,1)
x_predict.shape
# (7,4) - > (7,4,1)
result = model.predict(x_predict)
print("결과 \n",result)

결과 
 [[93.78084 ]
 [93.94304 ]
 [94.08988 ]
 [94.223045]
 [94.34403 ]
 [94.45416 ]
 [94.55456 ]]


In [152]:
test = np.array([[[96],[97],[98],[99]]])

# print(test.shape)

result = model.predict(test)
print("결과",result)

결과 [[93.780846]]


In [151]:
loss = model.evaluate(x_test,y_test)

print(loss)



1/1 [==============================] - 1s 661ms/step - loss: 0.8590
0.8589988350868225
