In [10]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU

dataset = np.array([1,2,3,4,5,6,7])

In [11]:
# x = np.array([[i,i+1,i+2] for i in dataset])
# y = np.array([i+3 for i in dataset])

x = np.array([
 [1 ,2 ,3],
 [2 ,3 ,4],
 [3 ,4 ,5],
 [4 ,5 ,6],
 [5 ,6 ,7],
 [6 ,7 ,8],
 [7 ,8 ,9],
 [8,9,10],
 [20,30,40],
 [30,40,50],
 [40,50,60]])

y = np.array([4,5,6,7,8,9,10,11,50,60,70])



print(x)
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [20 30 40]
 [30 40 50]
 [40 50 60]]
[ 4  5  6  7  8  9 10 11 50 60 70]


In [12]:
print(x.shape,y.shape)

(11, 3) (11,)


In [13]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),3,1)
x

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]]])

In [14]:
print(x.shape,y.shape)

(11, 3, 1) (11,)


In [15]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    GRU(128,input_shape=(3,1)),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_1 (GRU)                 (None, 128)               50304     
                                                                 
 dense_2 (Dense)             (None, 16)                2064      
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 52,385
Trainable params: 52,385
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
11/11 [==============================] - 1s 4ms/step - loss: 21.8173
Epoch 2/100
11/11 [==============================] - 0s 4ms/step - loss: 20.9794
Epoch 3/100
11/11 [==============================] - 0s 4ms/step - loss: 20.1958
Epoch 4/100
11/11 [==============================] - 0s 5ms/step - loss: 18.8837
Epoch 5/100
11/11 [==============================] - 0s 4ms/step - loss: 16.5714
Epoch 6/100
11/11 [==============================] - 0s 6ms/step - loss: 15.4374
Epoch 7/100
11/11 [==============================] - 0s 4ms/step - loss: 14.9945
Epoch 8/100
11/11 [==============================] - 0s 3ms/step - loss: 14.4161
Epoch 9/100
11/11 [==============================] - 0s 6ms/step - loss: 14.0338
Epoch 10/100
11/11 [==============================] - 0s 4ms/step - loss: 13.7004
Epoch 11/100
11/11 [==============================] - 0s 5ms/step - loss: 13.6702
Epoch 12/100
11/11 [==============================] - 0s 4ms/step - loss: 13.1680
Epoch 13/100
11/11 [=====

In [17]:
loss = model.evaluate(x,y)

print(loss)



1/1 [==============================] - 0s 279ms/step - loss: 1.4312
1.4312052726745605


In [18]:
test = np.array([[[50],[60],[70]]])
result = model.predict(test)
print("결과",result)

결과 [[73.73273]]
