import numpy as np
from tensorflow.keras.models improt Sequential

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN

dataset = np.array([1,2,3,4,5,6,7])

In [2]:
x = np.array([[i,i+1,i+2] for i in dataset])
y = np.array([i+3 for i in dataset])

# x = np.array([
#  [1 ,2 ,3],
#  [2 ,3 ,4],
#  [3 ,4 ,5],
#  [4 ,5 ,6],
#  [5 ,6 ,7],
#  [6 ,7 ,8],
#  [7 ,8 ,9]])
# y = np.array([4,5,6,7,8,9,10])



print(x)
print(y)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[ 4  5  6  7  8  9 10]


In [3]:
print(x.shape,y.shape)

(7, 3) (7,)


In [4]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(7,3,1)
x

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]],

       [[5],
        [6],
        [7]],

       [[6],
        [7],
        [8]],

       [[7],
        [8],
        [9]]])

In [5]:
print(x.shape,y.shape)

(7, 3, 1) (7,)


In [11]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    SimpleRNN(64,input_shape=(3,1)),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 : 
# ( unit 개수 ) * (unit 개수 + feature 개수 + 1)
# 이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 64)                4224      
                                                                 
 dense_4 (Dense)             (None, 16)                1040      
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 5,281
Trainable params: 5,281
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
7/7 [==============================] - 5s 4ms/step - loss: 5.5180
Epoch 2/100
7/7 [==============================] - 0s 3ms/step - loss: 4.1084
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 2.9427
Epoch 4/100
7/7 [==============================] - 0s 4ms/step - loss: 1.8760
Epoch 5/100
7/7 [==============================] - 0s 5ms/step - loss: 1.8117
Epoch 6/100
7/7 [==============================] - 0s 5ms/step - loss: 1.4565
Epoch 7/100
7/7 [==============================] - 0s 5ms/step - loss: 1.4431
Epoch 8/100
7/7 [==============================] - 0s 5ms/step - loss: 1.4210
Epoch 9/100
7/7 [==============================] - 0s 4ms/step - loss: 1.3227
Epoch 10/100
7/7 [==============================] - 0s 5ms/step - loss: 1.2070
Epoch 11/100
7/7 [==============================] - 0s 4ms/step - loss: 1.1214
Epoch 12/100
7/7 [==============================] - 0s 5ms/step - loss: 1.0095
Epoch 13/100
7/7 [==============================] - 0s 4ms/st

In [8]:
loss = model.evaluate(x,y)

print(loss)



1/1 [==============================] - 0s 153ms/step - loss: 0.2677
0.26769939064979553


In [9]:
test = np.array([[[8],[9],[10]]])
result = model.predict(test)
print("[[8],[9],[10]]의 결과",result)

[[8],[9],[10]]의 결과 [[10.410141]]
