In [85]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,GRU

a = np.array(range(1,11))

def split_x(dataset,timesteps) : 
    tmp = []
    for i in range(len(dataset)-timesteps + 1):
        subset = dataset[i : (i+ timesteps)]
        tmp.append(subset)
    return np.array(tmp)

bbb = split_x(a,5)

print(bbb.shape)

x = bbb[:,:-1]
y = bbb[:,-1]
print(x,"\n",y)

(6, 5)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 [ 5  6  7  8  9 10]


In [86]:
print(x.shape,y.shape)

(6, 4) (6,)


In [87]:
# 모델을 리쉐이프해서 7개 데이터 를 (3,1) 로 만들자
x = x.reshape(len(x),4,1)
x

array([[[1],
        [2],
        [3],
        [4]],

       [[2],
        [3],
        [4],
        [5]],

       [[3],
        [4],
        [5],
        [6]],

       [[4],
        [5],
        [6],
        [7]],

       [[5],
        [6],
        [7],
        [8]],

       [[6],
        [7],
        [8],
        [9]]])

In [88]:
print(x.shape,y.shape)

(6, 4, 1) (6,)


In [89]:
# RNN 모델구성
model = Sequential([
    # input_shape 는 행 무시 
    # LSTM 은 3차원을 -> 2차원으로 변환함 flatten 필요없다
    # 따라서 LSTM 을 두번쓰면 오류발생
    
    LSTM(64,input_shape=(4,1),return_sequences=True),
    LSTM(32),
    Dense(16,activation="relu"),
    Dense(1)
])
# 파라미터의 값 :
# RNN x 4 (출력 , 입력 ,삭제게이트)
# ( unit 개수 ) * (unit 개수 + feature 개수)*4
# 기본 rnn ㅇㅇ이처럼 파라미터의 값이 매우 많아서 연산량이 매우 많다
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_12 (LSTM)              (None, 4, 64)             16896     
                                                                 
 lstm_13 (LSTM)              (None, 32)                12416     
                                                                 
 dense_12 (Dense)            (None, 16)                528       
                                                                 
 dense_13 (Dense)            (None, 1)                 17        
                                                                 
Total params: 29,857
Trainable params: 29,857
Non-trainable params: 0
_________________________________________________________________


In [90]:
# 컴파일 훈련
model.compile(loss="mae",optimizer="adam")
model.fit(x,y,epochs=100,batch_size=1)

Epoch 1/100
6/6 [==============================] - 2s 5ms/step - loss: 7.2912
Epoch 2/100
6/6 [==============================] - 0s 5ms/step - loss: 6.7484
Epoch 3/100
6/6 [==============================] - 0s 5ms/step - loss: 6.0033
Epoch 4/100
6/6 [==============================] - 0s 5ms/step - loss: 5.0833
Epoch 5/100
6/6 [==============================] - 0s 6ms/step - loss: 3.8847
Epoch 6/100
6/6 [==============================] - 0s 6ms/step - loss: 2.4152
Epoch 7/100
6/6 [==============================] - 0s 5ms/step - loss: 1.1263
Epoch 8/100
6/6 [==============================] - 0s 5ms/step - loss: 1.1245
Epoch 9/100
6/6 [==============================] - 0s 6ms/step - loss: 1.2354
Epoch 10/100
6/6 [==============================] - 0s 5ms/step - loss: 1.1940
Epoch 11/100
6/6 [==============================] - 0s 5ms/step - loss: 1.1513
Epoch 12/100
6/6 [==============================] - 0s 5ms/step - loss: 0.9693
Epoch 13/100
6/6 [==============================] - 0s 5ms/st

In [91]:
loss = model.evaluate(x,y)

print(loss)



1/1 [==============================] - 1s 501ms/step - loss: 0.1433
0.14330339431762695


In [92]:
test = np.array([[7,8,9,10]])
result = model.predict(test)
print("결과",result)

결과 [[10.2948885]]
