In [44]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split


In [45]:
# 2.데이터 정의
x= np.array([range(10),range(21,31),range(201,211)])
y = np.array([[i for i in range(1,11,1)],
             [1,1,1,1,2,1.3,1.4,1.5,1.6,1.4]])
x = x.T
y = y.T

x_train, x_test, y_train, y_test = train_test_split(
    x, 
    y, 
    test_size = 0.3, 
    shuffle = True, 
    # random_state = 123
    )

print("x_train: \n",x_train)
print("x_test: \n",x_test)
print("y_train: \n",y_train)
print("y_test: \n",y_test)



x_train: 
 [[  4  25 205]
 [  8  29 209]
 [  9  30 210]
 [  1  22 202]
 [  6  27 207]
 [  0  21 201]
 [  3  24 204]]
x_test: 
 [[  2  23 203]
 [  5  26 206]
 [  7  28 208]]
y_train: 
 [[ 5.   2. ]
 [ 9.   1.6]
 [10.   1.4]
 [ 2.   1. ]
 [ 7.   1.4]
 [ 1.   1. ]
 [ 4.   1. ]]
y_test: 
 [[3.  1. ]
 [6.  1.3]
 [8.  1.5]]


In [46]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(number1,input_dim = 3),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(2)
])

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_36 (Dense)            (None, 9)                 36        
                                                                 
 dense_37 (Dense)            (None, 9)                 90        
                                                                 
 dense_38 (Dense)            (None, 2)                 20        
                                                                 
 dense_39 (Dense)            (None, 8)                 24        
                                                                 
 dense_40 (Dense)            (None, 2)                 18        
                                                                 
Total params: 188
Trainable params: 188
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import numpy as np

print(np.__version__)

1.21.5


In [47]:
# 3. 컴파일과훈련
model.compile(loss="mse" , optimizer="adam")
model.fit(x_train,y_train,epochs=100,steps_per_epoch=100)

Epoch 1/100
100/100 [==============================] - 0s 705us/step - loss: 318.8980
Epoch 2/100
100/100 [==============================] - 0s 546us/step - loss: 5.8188
Epoch 3/100
100/100 [==============================] - 0s 530us/step - loss: 3.8898
Epoch 4/100
100/100 [==============================] - 0s 601us/step - loss: 2.6202
Epoch 5/100
100/100 [==============================] - 0s 647us/step - loss: 1.0990
Epoch 6/100
100/100 [==============================] - 0s 648us/step - loss: 0.5728
Epoch 7/100
100/100 [==============================] - 0s 588us/step - loss: 0.4893
Epoch 8/100
100/100 [==============================] - 0s 176us/step - loss: 0.4893


In [48]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

1/1 [==============================] - 0s 61ms/step - loss: 0.1868
loss :  0.18679523468017578


In [49]:
model.predict([[0,21,201]])

array([[2.0035393, 1.7919153]], dtype=float32)