In [17]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split


In [18]:
# 2.데이터 정의
x = np.array([1,2,3,4,5,6,7,8,9,10]) 
y= np.array(range(10))

x_train, x_test, y_train, y_test = train_test_split(
    x, 
    y, 
    test_size = 0.3, 
    shuffle = True, 
    random_state = 21
    )

print(x_train)
print(y_train)

print(x_test)
print(y_test)

[ 4  6  7  1  5  9 10]
[3 5 6 0 4 8 9]
[2 3 8]
[1 2 7]


In [19]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(number1,input_dim = 1),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(1)
])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 1)                 2         
                                                                 
 dense_11 (Dense)            (None, 1)                 2         
                                                                 
 dense_12 (Dense)            (None, 4)                 8         
                                                                 
 dense_13 (Dense)            (None, 2)                 10        
                                                                 
 dense_14 (Dense)            (None, 1)                 3         
                                                                 
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [20]:
# 3. 컴파일과훈련
model.compile(loss="mse" , optimizer="adam")
model.fit(x_train,y_train,epochs=100,steps_per_epoch=100)

Epoch 1/100
100/100 [==============================] - 0s 584us/step - loss: 5.0762
Epoch 2/100
100/100 [==============================] - 0s 575us/step - loss: 0.4972
Epoch 3/100
100/100 [==============================] - 0s 601us/step - loss: 0.3471
Epoch 4/100
100/100 [==============================] - 0s 575us/step - loss: 0.2816
Epoch 5/100
100/100 [==============================] - 0s 547us/step - loss: 0.2239
Epoch 6/100
100/100 [==============================] - 0s 583us/step - loss: 0.1729
Epoch 7/100
100/100 [==============================] - 0s 585us/step - loss: 0.1203
Epoch 8/100
100/100 [==============================] - 0s 192us/step - loss: 0.1203


In [21]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

1/1 [==============================] - 0s 65ms/step - loss: 0.1581
loss :  0.15813182294368744


In [23]:
model.predict([11])

array([[9.597212]], dtype=float32)

In [24]:
import numpy as np

print(np.__version__)

1.21.5
