In [26]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense



In [27]:
# 2.데이터 정의


x = np.array([1,2,3,4,5,6,7,8,9,10]) 
y= np.array(range(10))

# 파이썬 슬라이씽 
x_train = x[:7]
y_train = y[:7]
# y_train = y [:-3]

x_test = x[7:]
y_test = y[-3:]


print(x_train)
print(y_train)

print(x_test)
print(y_test)


# x_train = x_train.T 
# y_train = y_train.T 

# # 칼럼을 하날만


[1 2 3 4 5 6 7]
[0 1 2 3 4 5 6]
[ 8  9 10]
[7 8 9]


In [28]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(number1,input_dim = 1),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(1)
])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 9)                 18        
                                                                 
 dense_16 (Dense)            (None, 9)                 90        
                                                                 
 dense_17 (Dense)            (None, 4)                 40        
                                                                 
 dense_18 (Dense)            (None, 9)                 45        
                                                                 
 dense_19 (Dense)            (None, 1)                 10        
                                                                 
Total params: 203
Trainable params: 203
Non-trainable params: 0
_________________________________________________________________


In [29]:
# 3. 컴파일과훈련
model.compile(loss="mse" , optimizer="adam")
model.fit(x_train,y_train,epochs=100,steps_per_epoch=100)

Epoch 1/100
100/100 [==============================] - 0s 656us/step - loss: -32.3781 - accuracy: 0.2800
Epoch 2/100
100/100 [==============================] - 0s 693us/step - loss: -32.4032 - accuracy: 0.2900
Epoch 3/100
100/100 [==============================] - 0s 706us/step - loss: -33.1840 - accuracy: 0.2900
Epoch 4/100
100/100 [==============================] - 0s 720us/step - loss: -32.2964 - accuracy: 0.2800
Epoch 5/100
100/100 [==============================] - 0s 657us/step - loss: -32.6235 - accuracy: 0.2900
Epoch 6/100
100/100 [==============================] - 0s 720us/step - loss: -32.7853 - accuracy: 0.2800
Epoch 7/100
100/100 [==============================] - 0s 699us/step - loss: -32.7859 - accuracy: 0.2900
Epoch 8/100
100/100 [==============================] - 0s 139us/step - loss: -32.7859 - accuracy: 0.2900


In [30]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

1/1 [==============================] - 0s 91ms/step - loss: -106.7447 - accuracy: 0.0000e+00
loss :  [-106.74466705322266, 0.0]


In [31]:
model.predict([11])

array([[11.766961]], dtype=float32)