In [247]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 1.데이터
x= np.array([range(21,31),range(10),range(201,211)])
y = np.array([[i for i in range(1,11,1)],
             [1,1,1,1,2,1.3,1.4,1.5,1.6,1.4]])
x = x.T
y = y.T

print(x.shape)
print(x)
print(y.shape)
print(y)

(10, 3)
[[ 21   0 201]
 [ 22   1 202]
 [ 23   2 203]
 [ 24   3 204]
 [ 25   4 205]
 [ 26   5 206]
 [ 27   6 207]
 [ 28   7 208]
 [ 29   8 209]
 [ 30   9 210]]
(10, 2)
[[ 1.   1. ]
 [ 2.   1. ]
 [ 3.   1. ]
 [ 4.   1. ]
 [ 5.   2. ]
 [ 6.   1.3]
 [ 7.   1.4]
 [ 8.   1.5]
 [ 9.   1.6]
 [10.   1.4]]


In [248]:
# 2. 모델구성하기

from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(5,input_dim = 3),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(2)
])

model.summary()

Model: "sequential_58"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_305 (Dense)           (None, 5)                 20        
                                                                 
 dense_306 (Dense)           (None, 7)                 42        
                                                                 
 dense_307 (Dense)           (None, 7)                 56        
                                                                 
 dense_308 (Dense)           (None, 5)                 40        
                                                                 
 dense_309 (Dense)           (None, 2)                 12        
                                                                 
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________


In [249]:
# 3. 모델 컴파일 + 훈련
model.compile(loss="mae",optimizer ="adam")

model.fit(x,y,epochs = 100, steps_per_epoch = 100)

Epoch 1/100
100/100 [==============================] - 0s 655us/step - loss: 2.6781
Epoch 2/100
100/100 [==============================] - 0s 640us/step - loss: 1.9057
Epoch 3/100
100/100 [==============================] - 0s 629us/step - loss: 1.6867
Epoch 4/100
100/100 [==============================] - 0s 641us/step - loss: 1.5069
Epoch 5/100
100/100 [==============================] - 0s 650us/step - loss: 1.3586
Epoch 6/100
100/100 [==============================] - 0s 644us/step - loss: 1.1835
Epoch 7/100
100/100 [==============================] - 0s 644us/step - loss: 1.0251
Epoch 8/100
100/100 [==============================] - 0s 635us/step - loss: 0.6530
Epoch 9/100
100/100 [==============================] - 0s 655us/step - loss: 0.3705
Epoch 10/100
100/100 [==============================] - 0s 691us/step - loss: 0.1957
Epoch 11/100
100/100 [==============================] - 0s 150us/step - loss: 0.1957


In [250]:
# 평가
loss = model.evaluate(x,y)
print(model.predict([[30,9,210]]))

1/1 [==============================] - 0s 58ms/step - loss: 0.2747
[[9.622087  1.6039934]]
