In [29]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split


In [40]:
# 1 데이터 정리
x = np.array(range(1,21))
y = np.array([1,2,4,3,5,7,9,3,8,12,13,8,14,15,9,6,17,23,21,20])

# 2.as_integer_ratio
x_train, x_test,y_train,y_test = train_test_split(x,y,
    train_size=0.7,
    shuffle = True,
    random_state= 123
)

print(x_train)
print(y_train)
print(x_test)
print(y_test)

[20 13  1 16 17 10 12 11  4  2  7 19  3 14]
[20 14  1  6 17 12  8 13  3  2  9 21  4 15]
[15  6  5 18  9  8]
[ 9  7  5 23  8  3]


In [31]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)

model = Sequential([
    Dense(number1,input_dim = 1),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(1)
])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            (None, 2)                 4         
                                                                 
 dense_21 (Dense)            (None, 2)                 6         
                                                                 
 dense_22 (Dense)            (None, 1)                 3         
                                                                 
 dense_23 (Dense)            (None, 4)                 8         
                                                                 
 dense_24 (Dense)            (None, 1)                 5         
                                                                 
Total params: 26
Trainable params: 26
Non-trainable params: 0
_________________________________________________________________


In [32]:
# RMSE 정의


In [33]:
# 3. 컴파일과훈련
# 메트릭스 안에는 loss 함수를 넣어서 참고할 수 있습니다. 훈련에는 영향을 미치지 않습니다.
model.compile(loss="mae" , optimizer="adam",metrics=["mae"])
model.fit(x_train,y_train,epochs=100,steps_per_epoch=10)

Epoch 1/100
10/10 [==============================] - 0s 790us/step - loss: 10.9242 - mae: 10.9242
Epoch 2/100
10/10 [==============================] - 0s 777us/step - loss: 11.7324 - mae: 11.7324
Epoch 3/100
10/10 [==============================] - 0s 775us/step - loss: 10.8905 - mae: 10.8905
Epoch 4/100
10/10 [==============================] - 0s 886us/step - loss: 9.6027 - mae: 9.6027
Epoch 5/100
10/10 [==============================] - 0s 776us/step - loss: 10.0603 - mae: 10.0603
Epoch 6/100
10/10 [==============================] - 0s 887us/step - loss: 11.3354 - mae: 11.3354
Epoch 7/100
10/10 [==============================] - 0s 886us/step - loss: 9.4028 - mae: 9.4028
Epoch 8/100
10/10 [==============================] - 0s 662us/step - loss: 10.3325 - mae: 10.3325
Epoch 9/100
10/10 [==============================] - 0s 886us/step - loss: 9.0257 - mae: 9.0257
Epoch 10/100
10/10 [==============================] - 0s 772us/step - loss: 8.6596 - mae: 8.6596
Epoch 11/100
10/10 [=======

In [36]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

from sklearn.metrics import r2_score

y_predict =model.predict(x_test)
print("=================")
print(y_test)
print(y_predict)
print("=================")


r2 = r2_score(y_test,y_predict)

print("R2 : ",r2)

1/1 [==============================] - 0s 14ms/step - loss: 3.2209 - mae: 3.2209
loss :  [3.2208850383758545, 3.2208850383758545]
[ 9  7  5 23  8  3]
[[15.53619  ]
 [ 6.670094 ]
 [ 5.6849723]
 [18.491556 ]
 [ 9.625459 ]
 [ 8.640338 ]]
R2 :  0.6120709330473926


In [35]:
model.predict([1])

array([[1.7444878]], dtype=float32)