In [209]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
# 1. 데이터 
datasets = (load_iris())

x = pd.DataFrame(datasets["data"])
y = pd.DataFrame(datasets["target"])

In [210]:
# print(datasets.colums) 
print(x)    
print(y)
# print(x.describe)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
     0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]


In [211]:
# print(x.info())
# print(x.describe())
# 데이터 분리
x_train, x_test, y_train,y_test = train_test_split(x,y,
                                                   train_size=0.8,
                                                   shuffle = True,
                                                #  stratify 는 데이터 불균형을 해결해줌
                                                   stratify=y
                                                #    random_state=21
                                                   )


# print(x.columns)

# print(y_test)

In [212]:
model = Sequential([
    Dense(50,activation="relu",input_shape=(4,)),
    Dense(40,activation="relu") ,
    Dense(40,activation="relu") ,
    Dense(30,activation="relu") ,
    Dense(30,activation="relu") ,
    Dense(20,activation="relu") ,
    # 다중분류모델의 활성화 함수는 softmax 입니다
    Dense(3,activation="softmax")
])

In [213]:
# 이진분류는 마지막 활성함수는 sigmoid + loss 는 바이너리 크로스 엔트로피 

from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
monitor='val_loss',
min_delta=0.01, patience=5, 
verbose=1, 
mode='min')

# 훈련값이 int 형이기 때문에 sparse 를 사용합니다.
model.compile(loss="sparse_categorical_crossentropy"
              ,optimizer="adam"
              ,metrics=["accuracy"]
              )

hist = model.fit(x_train, y_train, epochs=100, batch_size=32, 
                 validation_split=0.2,
                 callbacks = [early_stopping])

# metrics 에 accuracy 사용가능


Epoch 1/100
3/3 [==============================] - 0s 63ms/step - loss: 1.0955 - accuracy: 0.3438 - val_loss: 1.0844 - val_accuracy: 0.2917
Epoch 2/100
3/3 [==============================] - 0s 13ms/step - loss: 1.0697 - accuracy: 0.3646 - val_loss: 1.0722 - val_accuracy: 0.3333
Epoch 3/100
3/3 [==============================] - 0s 13ms/step - loss: 1.0551 - accuracy: 0.5208 - val_loss: 1.0581 - val_accuracy: 0.5833
Epoch 4/100
3/3 [==============================] - 0s 14ms/step - loss: 1.0371 - accuracy: 0.6667 - val_loss: 1.0412 - val_accuracy: 0.5833
Epoch 5/100
3/3 [==============================] - 0s 13ms/step - loss: 1.0155 - accuracy: 0.6771 - val_loss: 1.0183 - val_accuracy: 0.6250
Epoch 6/100
3/3 [==============================] - 0s 13ms/step - loss: 0.9866 - accuracy: 0.6667 - val_loss: 0.9877 - val_accuracy: 0.5417
Epoch 7/100
3/3 [==============================] - 0s 14ms/step - loss: 0.9471 - accuracy: 0.6458 - val_loss: 0.9507 - val_accuracy: 0.5417
Epoch 8/100
3/3 [===

In [214]:
loss,accuracy = model.evaluate(x_test,y_test)

print("loss:",loss,"\nacc :" ,accuracy)


1/1 [==============================] - 0s 18ms/step - loss: 0.1034 - accuracy: 0.9667
loss: 0.10336845368146896 
acc : 0.9666666388511658


In [215]:
from sklearn.metrics import accuracy_score
y_predict = model.predict(x_test)

# predict 의 값은 소숫점값이라 정수형으로 바꿔줘야합니다.
print(y_predict[:5])

# argmax 는 x 를 최대값으로 만들어주는 입력을 구하는함수
y_predict = np.argmax(y_predict,axis=1)

print(y_predict[:5])


print("========================================")
acc = accuracy_score(y_test,y_predict)
print(acc)

[[1.7731037e-03 4.6307910e-02 9.5191896e-01]
 [1.2353468e-03 9.7605920e-01 2.2705484e-02]
 [3.1075401e-03 1.4896794e-01 8.4792453e-01]
 [1.8917341e-04 1.5831261e-03 9.9822766e-01]
 [9.9941349e-01 5.8613432e-04 3.6902728e-07]]
[2 1 2 2 0]
0.9666666666666667
