In [106]:
# 실습
# R2 를 음수가 아닌 0.5 이하로 줄이기
# 2. 데이터는 건들지 말것 
# 3. 레이어는 인풋 아웃풋 포함 7개 이상 
# 4. batch_size = 1
# 5. 히든레이어의 노드는 각각 10 개 이상 100 개 이하
# 6. train 70% 
# 7. epoch 100 번 이상
# 8. loss 지표는 mse or mae

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split


In [107]:
# 1 데이터 정리
x = np.array(range(1,21))
y = np.array([i for i in range(1,21)])

# 2.as_integer_ratio
x_train, x_test,y_train,y_test = train_test_split(x,y,
    train_size=0.7,
    shuffle = True,
    random_state= 123
)

print(x_train)
print(y_train)
print(x_test)
print(y_test)

[20 13  1 16 17 10 12 11  4  2  7 19  3 14]
[20 13  1 16 17 10 12 11  4  2  7 19  3 14]
[15  6  5 18  9  8]
[15  6  5 18  9  8]


In [108]:

# 2. 모델 구성
from random import randrange
from keras.layers import Dropout
number1 = randrange(10,100,1)
number2 = randrange(10,100,1)
number3 = randrange(10,100,1)
number4= randrange(10,100,1)
number5= randrange(10,100,1)
number6= randrange(10,100,1)
number7= randrange(10,100,1)

model = Sequential([
    Dense(number1,input_dim = 1),
    Dense(10),
    Dense(10),
    Dense(10),
    Dense(10),
    Dense(1),
  
]
         )
model.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2369 (Dense)          (None, 79)                158       
                                                                 
 dense_2370 (Dense)          (None, 100)               8000      
                                                                 
 dense_2371 (Dense)          (None, 10)                1010      
                                                                 
 dense_2372 (Dense)          (None, 100)               1100      
                                                                 
 dense_2373 (Dense)          (None, 10)                1010      
                                                                 
 dense_2374 (Dense)          (None, 100)               1100      
                                                                 
 dense_2375 (Dense)          (None, 10)              

In [109]:
# 3. 컴파일과훈련
# 메트릭스 안에는 loss 함수를 넣어서 참고할 수 있습니다. 훈련에는 영향을 미치지 않습니다.
model.compile(loss="mae" , optimizer="SGD")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
14/14 [==============================] - 1s 1ms/step - loss: 10.1032
Epoch 2/100
14/14 [==============================] - 0s 1ms/step - loss: 8.7631
Epoch 3/100
14/14 [==============================] - 0s 1ms/step - loss: 7.4459
Epoch 4/100
14/14 [==============================] - 0s 1ms/step - loss: 6.9842
Epoch 5/100
14/14 [==============================] - 0s 1ms/step - loss: 6.3747
Epoch 6/100
14/14 [==============================] - 0s 1ms/step - loss: 6.2944
Epoch 7/100
14/14 [==============================] - 0s 1ms/step - loss: 6.1062
Epoch 8/100
14/14 [==============================] - 0s 2ms/step - loss: 6.3081
Epoch 9/100
14/14 [==============================] - 0s 2ms/step - loss: 5.7233
Epoch 10/100
14/14 [==============================] - 0s 1ms/step - loss: 6.3489
Epoch 11/100
14/14 [==============================] - 0s 2ms/step - loss: 6.4530
Epoch 12/100
14/14 [==============================] - 0s 2ms/step - loss: 6.1143
Epoch 13/100
14/14 [================

In [110]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

from sklearn.metrics import r2_score

y_predict =model.predict(x_test)
print("=================")
print(y_test)
print(y_predict)
print("=================")


r2 = r2_score(y_test,y_predict)

print("R2 : ",r2)

1/1 [==============================] - 0s 287ms/step - loss: 4.9533
loss :  4.953310966491699
1/1 [==============================] - 0s 268ms/step
[15  6  5 18  9  8]
[[12.359932]
 [12.359933]
 [12.359933]
 [12.359932]
 [12.359932]
 [12.359932]]
R2 :  -0.21406058103705994


In [111]:
model.predict([1])

1/1 [==============================] - 0s 27ms/step


array([[12.359933]], dtype=float32)