In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense



In [19]:
# 2.데이터 정의


x = np.array([1,2,3,4,5,6,7,8,9,10]) 
y= np.array(range(10))

# 파이썬 슬라이씽 
x_train = x[:7]
y_train = y[:7]
# y_train = y [:-3]

x_test = x[7:]
y_test = y[-3:]


print(x_train)
print(y_train)

print(x_test)
print(y_test)


# x_train = x_train.T 
# y_train = y_train.T 

# # 칼럼을 하날만


[1 2 3 4 5 6 7]
[0 1 2 3 4 5 6]
[ 8  9 10]
[7 8 9]


In [11]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(number1,input_dim = 1),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(1)
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 7)                 14        
                                                                 
 dense_6 (Dense)             (None, 7)                 56        
                                                                 
 dense_7 (Dense)             (None, 6)                 48        
                                                                 
 dense_8 (Dense)             (None, 7)                 49        
                                                                 
 dense_9 (Dense)             (None, 1)                 8         
                                                                 
Total params: 175
Trainable params: 175
Non-trainable params: 0
_________________________________________________________________


In [12]:
# 3. 컴파일과훈련
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x_train,y_train,epochs=100,steps_per_epoch=100)

Epoch 1/100
100/100 [==============================] - 0s 631us/step - loss: 3.3075
Epoch 2/100
100/100 [==============================] - 0s 641us/step - loss: 0.4769
Epoch 3/100
100/100 [==============================] - 0s 680us/step - loss: 0.2542
Epoch 4/100
100/100 [==============================] - 0s 704us/step - loss: 0.1014
Epoch 5/100
100/100 [==============================] - 0s 620us/step - loss: 0.0251
Epoch 6/100
100/100 [==============================] - 0s 636us/step - loss: 0.0036
Epoch 7/100
100/100 [==============================] - 0s 737us/step - loss: 2.8645e-04
Epoch 8/100
100/100 [==============================] - 0s 209us/step - loss: 2.8645e-04


In [13]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

1/1 [==============================] - 0s 103ms/step - loss: 1.8511e-04
loss :  0.00018511316739022732


In [14]:
model.predict([11])

array([[9.980359]], dtype=float32)