In [3]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


In [4]:
x = np.array(range(1,17))
y = np.array(range(1,17))

In [5]:
# from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=1)
# x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=1)

In [6]:
print(x_train, x_train.shape)
print(x_test, x_test.shape)
# print(x_val, x_val.shape)

# print(x_train)
# print(x_test)
# print(x_val)

[13  7  1  3 16  6  9 10 12 15] (10,)
[ 4 14  8] (3,)
[11  5  2] (3,)


In [7]:
# 2. 모델구성

model = Sequential([
    
    Dense(10,input_dim = 1 ,activation="relu"),
    Dense(10,activation="relu"),
    Dense(10,activation="relu"),
    Dense(10,activation="relu"),
    Dense(10,activation="relu"),
    Dense(10,activation="relu"),
    Dense(10,activation="relu"),
    Dense(10,activation="relu"),
    Dense(10,activation="relu"),
    # 마지막 레이어는 통상 relu 넣지 않습니다. 히든레이어에 많이쓰임
    Dense(1),
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                20        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 10)                110       
                                                                 
 dense_3 (Dense)             (None, 10)                110       
                                                                 
 dense_4 (Dense)             (None, 10)                110       
                                                                 
 dense_5 (Dense)             (None, 10)                110       
                                                                 
 dense_6 (Dense)             (None, 10)                1

In [10]:
model.compile(loss='mse', optimizer = 'adam')
# fit 에서 validation 을 자동으로 분리해줌
model.fit(x_train, y_train, epochs=100, batch_size=1, validation_split=0.25)


Epoch 1/100
7/7 [==============================] - 0s 21ms/step - loss: 0.0121 - val_loss: 0.0010
Epoch 2/100
7/7 [==============================] - 0s 6ms/step - loss: 0.0020 - val_loss: 0.0052
Epoch 3/100
7/7 [==============================] - 0s 7ms/step - loss: 0.0044 - val_loss: 0.0393
Epoch 4/100
7/7 [==============================] - 0s 7ms/step - loss: 0.0176 - val_loss: 0.0038
Epoch 5/100
7/7 [==============================] - 0s 7ms/step - loss: 0.0028 - val_loss: 0.0013
Epoch 6/100
7/7 [==============================] - 0s 7ms/step - loss: 0.0017 - val_loss: 0.0040
Epoch 7/100
7/7 [==============================] - 0s 7ms/step - loss: 0.0015 - val_loss: 1.2614e-05
Epoch 8/100
7/7 [==============================] - 0s 7ms/step - loss: 3.3949e-04 - val_loss: 5.5485e-04
Epoch 9/100
7/7 [==============================] - 0s 7ms/step - loss: 7.7267e-04 - val_loss: 0.0061
Epoch 10/100
7/7 [==============================] - 0s 7ms/step - loss: 0.0038 - val_loss: 0.0039
Epoch 11/100