In [38]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split


In [39]:
# 2.데이터 정의
x= np.array([range(10),range(21,31),range(201,211)])
y = np.array([[i for i in range(1,11,1)],
             [1,1,1,1,2,1.3,1.4,1.5,1.6,1.4]])
x = x.T
y = y.T

x_train, x_test, y_train, y_test = train_test_split(
    x, 
    y, 
    test_size = 0.3, 
    shuffle = True, 
    # random_state = 123
    )

print("x_train: \n",x_train)
print("x_test: \n",x_test)
print("y_train: \n",y_train)
print("y_test: \n",y_test)



x_train: 
 [[  4  25 205]
 [  3  24 204]
 [  5  26 206]
 [  0  21 201]
 [  8  29 209]
 [  9  30 210]
 [  6  27 207]]
x_test: 
 [[  2  23 203]
 [  7  28 208]
 [  1  22 202]]
y_train: 
 [[ 5.   2. ]
 [ 4.   1. ]
 [ 6.   1.3]
 [ 1.   1. ]
 [ 9.   1.6]
 [10.   1.4]
 [ 7.   1.4]]
y_test: 
 [[3.  1. ]
 [8.  1.5]
 [2.  1. ]]


In [40]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(number1,input_dim = 3),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(2)
])

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_31 (Dense)            (None, 9)                 36        
                                                                 
 dense_32 (Dense)            (None, 9)                 90        
                                                                 
 dense_33 (Dense)            (None, 2)                 20        
                                                                 
 dense_34 (Dense)            (None, 6)                 18        
                                                                 
 dense_35 (Dense)            (None, 2)                 14        
                                                                 
Total params: 178
Trainable params: 178
Non-trainable params: 0
_________________________________________________________________


In [41]:
# 3. 컴파일과훈련
model.compile(loss="mse" , optimizer="adam")
model.fit(x_train,y_train,epochs=100,steps_per_epoch=100)

Epoch 1/100
100/100 [==============================] - 0s 651us/step - loss: 385.1900
Epoch 2/100
100/100 [==============================] - 0s 639us/step - loss: 12.0525
Epoch 3/100
100/100 [==============================] - 0s 625us/step - loss: 11.4726
Epoch 4/100
100/100 [==============================] - 0s 638us/step - loss: 10.5079
Epoch 5/100
100/100 [==============================] - 0s 606us/step - loss: 9.6324
Epoch 6/100
100/100 [==============================] - 0s 659us/step - loss: 9.0986
Epoch 7/100
100/100 [==============================] - 0s 634us/step - loss: 7.6128
Epoch 8/100
100/100 [==============================] - 0s 169us/step - loss: 7.6128


In [42]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

1/1 [==============================] - 0s 78ms/step - loss: 8.0725
loss :  8.072535514831543


In [43]:
model.predict([[0,21,201]])

array([[7.421847 , 1.4427552]], dtype=float32)