In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split


In [6]:
# 2.데이터 정의
x= np.array([range(10),range(21,31),range(201,211)])
y = np.array([[i for i in range(1,11,1)],
             [1,1,1,1,2,1.3,1.4,1.5,1.6,1.4]])
x = x.T
y = y.T

x_train, x_test, y_train, y_test = train_test_split(
    x, 
    y, 
    test_size = 0.3, 
    shuffle = True, 
    # random_state = 123
    )

print("x_train: \n",x_train)
print("x_test: \n",x_test)
print("y_train: \n",y_train)
print("y_test: \n",y_test)



x_train: 
 [[  7  28 208]
 [  1  22 202]
 [  9  30 210]
 [  2  23 203]
 [  6  27 207]
 [  8  29 209]
 [  5  26 206]]
x_test: 
 [[  0  21 201]
 [  3  24 204]
 [  4  25 205]]
y_train: 
 [[ 8.   1.5]
 [ 2.   1. ]
 [10.   1.4]
 [ 3.   1. ]
 [ 7.   1.4]
 [ 9.   1.6]
 [ 6.   1.3]]
y_test: 
 [[1. 1.]
 [4. 1.]
 [5. 2.]]


In [4]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(number1,input_dim = 3),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(1)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 6         
                                                                 
 dense_1 (Dense)             (None, 3)                 12        
                                                                 
 dense_2 (Dense)             (None, 9)                 36        
                                                                 
 dense_3 (Dense)             (None, 4)                 40        
                                                                 
 dense_4 (Dense)             (None, 1)                 5         
                                                                 
Total params: 99
Trainable params: 99
Non-trainable params: 0
_________________________________________________________________


In [5]:
# 3. 컴파일과훈련
model.compile(loss="mse" , optimizer="adam")
model.fit(x_train,y_train,epochs=100,steps_per_epoch=100)

Epoch 1/100


ValueError: in user code:

    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\bitcamp\anaconda3\envs\tf27\lib\site-packages\keras\engine\input_spec.py", line 247, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer "sequential" (type Sequential).
    
    Input 0 of layer "dense" is incompatible with the layer: expected axis -1of input shape to have value 1, but received input with shape (1, 3)
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(1, 3), dtype=int32)
      • training=True
      • mask=None


In [ ]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

1/1 [==============================] - 0s 60ms/step - loss: 0.2876
loss :  0.28762954473495483


In [ ]:
model.predict([11])

array([[9.438547]], dtype=float32)

In [ ]:
import numpy as np

print(np.__version__)

1.21.5
