In [4]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split


In [10]:
# 2.데이터 정의


x = np.array([1,2,3,4,5,6,7,8,9,10]) 
y= np.array(range(10))

x_train, x_test, y_train, y_test = train_test_split(x, 
                                                    y, 
                                                    test_size = 0.3, 
                                                    shuffle = True, 
                                                    random_state = 21)

print(x_train)
print(y_train)

print(x_test)
print(y_test)

[ 4  6  7  1  5  9 10]
[3 5 6 0 4 8 9]
[2 3 8]
[1 2 7]


In [6]:

# 2. 모델 구성
from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(number1,input_dim = 1),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(1)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 10        
                                                                 
 dense_1 (Dense)             (None, 5)                 30        
                                                                 
 dense_2 (Dense)             (None, 4)                 24        
                                                                 
 dense_3 (Dense)             (None, 4)                 20        
                                                                 
 dense_4 (Dense)             (None, 1)                 5         
                                                                 
Total params: 89
Trainable params: 89
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 3. 컴파일과훈련
model.compile(loss="mse" , optimizer="adam")
model.fit(x_train,y_train,epochs=100,steps_per_epoch=100)

Epoch 1/100
100/100 [==============================] - 0s 625us/step - loss: 16.0296
Epoch 2/100
100/100 [==============================] - 0s 611us/step - loss: 0.4678
Epoch 3/100
100/100 [==============================] - 0s 568us/step - loss: 0.3970
Epoch 4/100
100/100 [==============================] - 0s 598us/step - loss: 0.3215
Epoch 5/100
100/100 [==============================] - 0s 551us/step - loss: 0.2571
Epoch 6/100
100/100 [==============================] - 0s 608us/step - loss: 0.1768
Epoch 7/100
100/100 [==============================] - 0s 585us/step - loss: 0.1353
Epoch 8/100
100/100 [==============================] - 0s 241us/step - loss: 0.1353


In [8]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

1/1 [==============================] - 0s 102ms/step - loss: 0.1715
loss :  0.17153362929821014


In [9]:
model.predict([11])

array([[9.611277]], dtype=float32)