In [264]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 1.데이터
x= np.array([range(21,31),range(10),range(201,211)])
y = np.array([[i for i in range(1,11,1)],
             [1,1,1,1,2,1.3,1.4,1.5,1.6,1.4]])
x = x.T
y = y.T

print(x.shape)
print(x)
print(y.shape)
print(y)

(10, 3)
[[ 21   0 201]
 [ 22   1 202]
 [ 23   2 203]
 [ 24   3 204]
 [ 25   4 205]
 [ 26   5 206]
 [ 27   6 207]
 [ 28   7 208]
 [ 29   8 209]
 [ 30   9 210]]
(10, 2)
[[ 1.   1. ]
 [ 2.   1. ]
 [ 3.   1. ]
 [ 4.   1. ]
 [ 5.   2. ]
 [ 6.   1.3]
 [ 7.   1.4]
 [ 8.   1.5]
 [ 9.   1.6]
 [10.   1.4]]


In [265]:
# 2. 모델구성하기

from random import randrange
number1 = randrange(1,10,1)
number2 = randrange(1,10,1)
number3= randrange(1,10,1)
model = Sequential([
    Dense(5,input_dim = 3),
    Dense(number1),
    Dense(number2),
    Dense(number3),
    Dense(2)
])

model.summary()

Model: "sequential_62"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_325 (Dense)           (None, 5)                 20        
                                                                 
 dense_326 (Dense)           (None, 3)                 18        
                                                                 
 dense_327 (Dense)           (None, 5)                 20        
                                                                 
 dense_328 (Dense)           (None, 5)                 30        
                                                                 
 dense_329 (Dense)           (None, 2)                 12        
                                                                 
Total params: 100
Trainable params: 100
Non-trainable params: 0
_________________________________________________________________


In [266]:
# 3. 모델 컴파일 + 훈련
model.compile(loss="mse",optimizer ="adam")

model.fit(x,y,epochs = 100, steps_per_epoch = 100)

Epoch 1/100
100/100 [==============================] - 0s 680us/step - loss: 23.5589
Epoch 2/100
100/100 [==============================] - 0s 663us/step - loss: 4.2314
Epoch 3/100
100/100 [==============================] - 0s 652us/step - loss: 3.4070
Epoch 4/100
100/100 [==============================] - 0s 696us/step - loss: 2.1385
Epoch 5/100
100/100 [==============================] - 0s 663us/step - loss: 1.3899
Epoch 6/100
100/100 [==============================] - 0s 666us/step - loss: 1.0534
Epoch 7/100
100/100 [==============================] - 0s 650us/step - loss: 0.5517
Epoch 8/100
100/100 [==============================] - 0s 621us/step - loss: 0.4342
Epoch 9/100
100/100 [==============================] - 0s 664us/step - loss: 0.2184
Epoch 10/100
100/100 [==============================] - 0s 660us/step - loss: 0.1060
Epoch 11/100
100/100 [==============================] - 0s 160us/step - loss: 0.1060


In [270]:
# 평가
loss = model.evaluate(x,y)
print(model.predict([[30,9,210]]))

1/1 [==============================] - 0s 13ms/step - loss: 0.0849
[[9.442846  1.7981524]]
