In [1]:
# 실습
# R2 를 음수가 아닌 0.5 이하로 줄이기
# 2. 데이터는 건들지 말것 
# 3. 레이어는 인풋 아웃풋 포함 7개 이상 
# 4. batch_size = 1
# 5. 히든레이어의 노드는 각각 10 개 이상 100 개 이하
# 6. train 70% 
# 7. epoch 100 번 이상
# 8. loss 지표는 mse or mae

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split


In [2]:
# 1 데이터 정리
x = np.array(range(1,21))
y = np.array([i for i in range(1,21)])

# 2.as_integer_ratio
x_train, x_test,y_train,y_test = train_test_split(x,y,
    train_size=0.7,
    shuffle = True,
    random_state= 123
)

print(x_train)
print(y_train)
print(x_test)
print(y_test)

[20 13  1 16 17 10 12 11  4  2  7 19  3 14]
[20 13  1 16 17 10 12 11  4  2  7 19  3 14]
[15  6  5 18  9  8]
[15  6  5 18  9  8]


In [3]:

# 2. 모델 구성
from random import randrange
number1 = randrange(10,100,1)
number2 = randrange(10,100,1)
number3 = randrange(10,100,1)
number4= randrange(10,100,1)
number5= randrange(10,100,1)
number6= randrange(10,100,1)
number7= randrange(10,100,1)

model = Sequential([
    Dense(number1,input_dim = 1),
    Dense(10),
    Dense(10),
    Dense(10),
    Dense(10),
    Dense(1),
  
]
         )
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 33)                66        
                                                                 
 dense_1 (Dense)             (None, 10)                340       
                                                                 
 dense_2 (Dense)             (None, 10)                110       
                                                                 
 dense_3 (Dense)             (None, 10)                110       
                                                                 
 dense_4 (Dense)             (None, 10)                110       
                                                                 
 dense_5 (Dense)             (None, 1)                 11        
                                                                 
Total params: 747
Trainable params: 747
Non-trainable pa

In [4]:
# 3. 컴파일과훈련
# 메트릭스 안에는 loss 함수를 넣어서 참고할 수 있습니다. 훈련에는 영향을 미치지 않습니다.
model.compile(loss="mae" , optimizer="adam")
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
14/14 [==============================] - 0s 958us/step - loss: 0.7359
Epoch 2/100
14/14 [==============================] - 0s 844us/step - loss: 0.4082
Epoch 3/100
14/14 [==============================] - 0s 845us/step - loss: 0.7179
Epoch 4/100
14/14 [==============================] - 0s 933us/step - loss: 0.4104
Epoch 5/100
14/14 [==============================] - 0s 905us/step - loss: 0.5219
Epoch 6/100
14/14 [==============================] - 0s 911us/step - loss: 0.1765
Epoch 7/100
14/14 [==============================] - 0s 905us/step - loss: 0.1004
Epoch 8/100
14/14 [==============================] - 0s 883us/step - loss: 0.2423
Epoch 9/100
14/14 [==============================] - 0s 844us/step - loss: 0.1539
Epoch 10/100
14/14 [==============================] - 0s 856us/step - loss: 0.1542
Epoch 11/100
14/14 [==============================] - 0s 951us/step - loss: 0.0840
Epoch 12/100
14/14 [==============================] - 0s 816us/step - loss: 0.2156
Epoch 13/100


In [5]:
loss = model.evaluate(x_test,y_test)
print("loss : ",loss)

from sklearn.metrics import r2_score

y_predict =model.predict(x_test)
print("=================")
print(y_test)
print(y_predict)
print("=================")


r2 = r2_score(y_test,y_predict)

print("R2 : ",r2)

1/1 [==============================] - 0s 124ms/step - loss: 0.1274
loss :  0.1274164468050003
1/1 [==============================] - 0s 81ms/step
[15  6  5 18  9  8]
[[15.197074]
 [ 6.067368]
 [ 5.052954]
 [18.240309]
 [ 9.110602]
 [ 8.096191]]
R2 :  0.9990698538292615


In [6]:
model.predict([1])

1/1 [==============================] - 0s 33ms/step


array([[0.99530685]], dtype=float32)